version: "3.7"
# cria os serviços a serem utilizados
services:
  # insere as váriaveis do aplicativo
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # insere as váriaveis do banco de dados
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: ${DB_DATABSE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - laravel

# cria uma rede para gerenciar os containers
networks:
  laravel:
    driver: bridge